version: "3.8"
services:
  app:
    build: .
    image: oishitable
    container_name: oishitable-app
    restart: on-failure
    depends_on:
      - database
      - redis
      - rabbitmq
      - elasticsearch
    # .env 파일에 있는 민감한 정보들을 주입합니다.
    env_file:
      - .env
    environment:
      # DB 연결 정보는 inline으로, 나머지는 .env 파일에서 불러옵니다.
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/oishitable
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${ROOT_PW}
      # 아래 환경변수들은 application.properties에서 ${변수명} 형태로 매핑되어야 합니다.
      SPRING_DATA_REDIS_URL: ${REDIS_URL}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_JWT_SECRET_ACCESS: ${JWT_SECRET_ACCESS}
      SPRING_JWT_SECRET_REFRESH: ${JWT_SECRET_REFRESH}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_SMTP_STARTTLS_ENABLE}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      KAKAO_AUTH_CLIENT: ${KAKAO_AUTH_CLIENT}
      KAKAO_AUTH_REDIRECT: ${KAKAO_AUTH_REDIRECT}
      KAKAO_API_KEY: ${KAKAO_API_KEY}
      SPRING_ELASTICSEARCH_URIS: ${ELASTICSEARCH_URIS}
      SPRING_ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      SPRING_ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      SPRING_DATA_ELASTICSEARCH_REPOSITORIES_ENABLED: "true"
    ports:
      - "8080:8080"

  database:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: oishitable
      MYSQL_ROOT_PASSWORD: ${ROOT_PW}
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  mysql-data:
  elasticsearch-data: